chore: ts-node command does not work - use tsx (#850)
## Description

ts-node command does not work to run the cli, we need to use tsx

```bash
> npx ts-node src/cli.ts      
Error: Cannot find module '/Users/cmwylie19/kubernetes-fluent-client/src/generate.js' imported from /Users/cmwylie19/kubernetes-fluent-client/src/cli.ts
    at finalizeResolution (node:internal/modules/esm/resolve:274:11)
    at moduleResolve (node:internal/modules/esm/resolve:859:10)
    at defaultResolve (node:internal/modules/esm/resolve:983:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:799:12)
    at ModuleLoader.#cachedDefaultResolve (node:internal/modules/esm/loader:723:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:706:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:307:38)
    at ModuleJob.#link (node:internal/modules/esm/module_job:170:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/cmwylie19/kubernetes-fluent-client/src/generate.js'
}

> npx tsx src/cli.ts --version
0.0.0-development
```
## Related Issue

Fixes #

<!-- or -->

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Other (security config, docs update, etc)

## Checklist before merging

- [x] Test, docs, adr added or updated as needed
- [x] [Contributor Guide
Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request)
followed

Signed-off-by: Case Wylie <cmwylie19@defenseunicorns.com>